name: Build Asset
on: 
  workflow_dispatch:
    branches: 

jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update zip
        run: |
          zip pv_eyes.zip pv_eyes.py

      - name: Upload zip to action - avoid double-zip
        uses: actions/upload-artifact@v3
        with: 
          name: pv_eyes
          path: pv_eyes
          retention-days: 7
