name: Build Asset for Release
on: 
  release:
    types: [published]

jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update zip
        run: |
          zip pv_eyes.zip pv_eyes.py

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pv_eyes.zip
